# name: Secure EKS CI/CD
# on:
#   workflow_dispatch:
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Terraform Plan
#         run: terraform -chdir=terraform plan
#       - name: Checkov Scan
#         run: checkov -d terraform --external-checks-dir checkov-custom-policies